import z from "zod";

const CurrentTechnology = z.object({
    uid: z.string(),
    name: z.string(),
    category: z.string(),
});

const Organization = z.object({
    id: z.string(),
    name: z.string(),
    website_url: z.string(),
    angellist_url: z.string().nullable(),
    linkedin_url: z.string(),
    twitter_url: z.string().nullable(),
    facebook_url: z.string().nullable(),
    languages: z.array(z.string()),
    alexa_ranking: z.number().nullable(),
    phone: z.string().nullable(),
    linkedin_uid: z.string(),
    founded_year: z.number(),
    publicly_traded_symbol: z.string().nullable(),
    publicly_traded_exchange: z.string().nullable(),
    logo_url: z.string().nullable(),
    crunchbase_url: z.string().nullable(),
    primary_domain: z.string(),
    sic_codes: z.array(z.string()),
    naics_codes: z.array(z.string()),
    industry: z.string(),
    estimated_num_employees: z.number(),
    keywords: z.array(z.string()),
    organization_revenue_printed: z.string().nullable(),
    organization_revenue: z.number(),
    industries: z.array(z.string()),
    secondary_industries: z.array(z.string()),
    snippets_loaded: z.boolean(),
    industry_tag_id: z.string(),
    industry_tag_hash: z.record(z.string(), z.string()),
    retail_location_count: z.number(),
    raw_address: z.string(),
    street_address: z.string().nullable(),
    city: z.string(),
    state: z.string(),
    postal_code: z.string(),
    country: z.string(),
    owned_by_organization_id: z.string().nullable(),
    num_languages: z.number(),
    num_retail_locations: z.number(),
    short_description: z.string(),
    total_funding: z.number().nullable(),
    total_funding_printed: z.string().nullable(),
    latest_funding_round_date: z.string().nullable(),
    latest_funding_stage: z.string().nullable(),
    latest_funding_detected_at: z.string().nullable(),
    funding_events: z.array(z.unknown()),
    suborganizations: z.array(z.unknown()),
    num_suborganizations: z.number(),
    technology_names: z.array(z.string()),
    current_technologies: z.array(CurrentTechnology),
    org_chart_root_people_ids: z.array(z.string()),
    org_chart_sector: z.string(),
    org_chart_removed: z.boolean().nullable(),
    org_chart_show_department_filter: z.boolean().nullable(),
    is_placeholder_organization: z.boolean().nullable(),
    departmental_head_count: z.record(z.string(), z.number()),
    organization_headcount_six_month_growth: z.number(),
    organization_headcount_twelve_month_growth: z.number(),
    organization_headcount_twenty_four_month_growth: z.number(),
});

export const ApolloResponse = z.object({
    organization: Organization,
});